language: csharp
mono: none
dotnet: 2.1

env:
  global:

before_install: 
 - cd commercetools.Sdk

install:
 - dotnet restore

script:
 - dotnet build -c Release
 - dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests --no-build -c Release
 - dotnet test commercetools.Sdk.Serialization.Tests --no-build -c Release