language: csharp
mono: none
dotnet: 2.1

env:
  global:

before_install: 
 - cd commercetools.Sdk

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests
 - dotnet test commercetools.Sdk.Serialization.Tests