language: csharp
mono: none
dotnet: 2.1

before_install: 
 - cd commercetools.Sdk

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test commercetools.Sdk.HttpApi.Tests --no-build
 - dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests --no-build
 - dotnet test commercetools.Sdk.Serialization.Tests --no-build