language: csharp
sudo: false

dotnet: 2.1.4 # SDK version; includes runtime version 2.0.5. Need 2.0+ for netcoreapp2.0 tests.
mono: none # Need 5.2+ for the included MSBuild.

install:
 - dotnet restore


script:
  - dotnet build
