language: csharp
mono: none
dotnet: 2.1

before_install: 
 - cd commercetools.Sdk

install:
 - dotnet restore

script:
 - dotnet build -c Release
 - dotnet test commercetools.Sdk.HttpApi.Tests -c release
 - dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests --no-build -c release
 - dotnet test commercetools.Sdk.Serialization.Tests --no-build -c release