image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Appveyor"

# disable built-in tests.
test: off

artifacts:
# Store NuGet packages
- path: .\package\**\*.nupkg
  name: NuGet
# Store NUnit Test Results
- path: .\package\**\*.xml
  name: NUnit Test Results

deploy:
- provider: NuGet
  server: https://www.myget.org/F/commercetools-dotnet-sdk/api/v2/package
  api_key:
    secure: wODMBph/C6fpMj92W0EfeV0teSwNDK69RdAxys+4VHbEgv/Cqrwino+Q1rLGBc5w
  skip_symbols: true
  on:
    branch: master