image: Visual Studio 2017


build_script:
  - ps: cd commercetools.Sdk
  - ps: dotnet restore
  - ps: dotnet build -c Release

test_script:
  - ps: dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests/commercetools.Sdk.LinqToQueryPredicate.Tests.csproj --no-build -c Release
  - ps: dotnet test commercetools.Sdk.Serialization.Tests/commercetools.Sdk.Serialization.Tests.csproj --no-build -c Release