image: Visual Studio 2017


before_build:
  - ps: cd commercetools.Sdk
  - ps: dotnet restore

build_script:
  - ps: dotnet build -c Release

after_build:
  - ps: dotnet pack -c Release -o /pack/

test_script:
  - ps: dotnet test commercetools.Sdk.LinqToQueryPredicate.Tests/commercetools.Sdk.LinqToQueryPredicate.Tests.csproj --no-build -c Release
  - ps: dotnet test commercetools.Sdk.Serialization.Tests/commercetools.Sdk.Serialization.Tests.csproj --no-build -c Release

artifacts:
- path: /pack/**/*.nupkg
  name: NuGet Package